#!/usr/bin/env python3
from locale import getlocale
from os.path import realpath
from sys import argv, exit

from re import split
def capital (_str):
    if isinstance(_str, str):
        for i, char in enumerate(_str):
            if char.isalpha():
                return _str[0:i] + _str[i].upper() + _str[i+1:]
    return _str

def help (display=True):
    lang = getlocale()[0]
    if display:
        if lang[:2] != 'es':
            print (f' -v, --version\t\toutput version information and exit')
        else:
            print (f' -v, --version\t\tMuestra la información de versión')
    else:
        return 'hello world' if lang[:2] != 'es' else 'hola mundo'

real_file = realpath(__file__).split('/')[-1].split('.')[0]
version = 0.1

if len(argv) < 2:
    if realpath(__file__) != realpath(argv[0]):
        print()
        exit ()

command = argv[0].split('/')[-1].split('.')[0]
command = 'capitalize' if command == 'capital' else command
commands = ('capital', 'capitalize', 'lower', 'title', 'upper')
argv_str = ' '.join(argv[1:])
show = help(False)

if command == real_file:
    print (f'{command} {version}')
    for i, cmd in enumerate(commands):
        show = help(False)
        usage_text = 'Usage' if getlocale()[0][:2] != 'es' else 'Modo de uso'
        prev_text = usage_text + ': ' if i == 0 else ''
        _cmd = 'capitalize' if cmd == 'capital' else cmd
        result = getattr(show, _cmd)()
        if cmd == 'lower':
            show = show.upper()
        n = len(usage_text) + 2
        complet_input = cmd + ' ' + show
        print(f"{prev_text:<{n}}{complet_input:<23} → {result}")
else:
    if command in ('capital', 'capitalize'):
        print (capital(argv_str))
    elif command == 'title':
        list_text = argv[1:].copy()
        list_text = [capital(txt) for txt in list_text]
        argv_str = ' '.join(list_text)
        print (argv_str)
    else:
        print (getattr(argv_str, command)() + '\033[0m')
